services:
  # Front-end service (React)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://localhost:5000/api
    container_name: et-client
    ports:
      - "4173:4173"
    depends_on:
      - server
 
  # Back-end service (Node.js/Express)
  server:
    build:
      context: ./server # Path to the back-end Dockerfile
      dockerfile: Dockerfile
    container_name: et-server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm run start"

  # PostgreSQL database service
  postgres:
    image: postgres:15
    container_name: et-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-etdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: